name: Convert TransXChange to GTFS

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip zip

      - name: Install Python dependencies
        run: |
          # python -m pip install --upgrade pip
          pip install numpy==1.19.5
          pip install untangle==1.1.1
          pip install pandas==1.0.0
          pip install pyproj==2.4.2
          pip install transx2gtfs

      - name: Download input zip
        run: curl -L -o input.zip "${{ secrets.timetableURL }}"

      - name: Filter input files (U1/U2 only)
        run: |
          mkdir -p tmp_input
          unzip input.zip -d tmp_input/
          cd tmp_input
          # Delete non-U1/U2 files
          find . -type f ! -name 'U1*' ! -name 'U2*' -delete
          # Remove empty directories
          find . -type d -empty -delete
          # Check if any files remain
          if [ -z "$(find . -type f)" ]; then
            echo "Error: No files starting with U1/U2 found in input"
            exit 1
          fi
          zip -r ../filtered_input.zip *
          cd ..
          rm -rf tmp_input input.zip
          
      - name: Prepare NaPTAN data directory
        run: mkdir -p /tmp/transx2gtfs

      - name: Download and package NaPTAN dataset
        run: |
          # Download the CSV file
          curl -L -o /tmp/transx2gtfs/Stops.csv "https://beta-naptan.dft.gov.uk/Download/National/csv"
          
          # Create a ZIP archive containing the CSV
          cd /tmp/transx2gtfs
          zip NaPTAN_data.zip Stops.csv
          cd -
          
      - name: Convert to GTFS
        run: |
          python -c "import transx2gtfs; transx2gtfs.convert('filtered_input.zip', 'gtfs.zip')"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gtfs.zip
          git commit -m "Update GTFS file (filtered U1/U2 sources)"
          git push
