name: Convert TransXChange to GTFS

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip zip jq

      - name: Install transxchange2gtfs CLI tool
        run: npm install -g transxchange2gtfs

      - name: Download new JSON data
        run: curl -L -o new_dataset.json "${{ secrets.timetableURL }}"

      - name: Compare modified dates and conditionally download new file
        id: compare-dates
        run: |
          # Extract modified dates from the new and existing JSON files
          new_modified=$(jq -r '.modified' new_dataset.json)
          existing_modified=$(jq -r '.modified' rawdata/dataset.json)

          # Compare the modified dates
          if [[ "$new_modified" > "$existing_modified" ]]; then
            echo "New dataset is newer. Downloading the file."
            new_url=$(jq -r '.url' new_dataset.json)
            curl -L -o input.zip "$new_url"
            echo "newer=true" >> $GITHUB_ENV
          else
            echo "New dataset is not newer. Using existing data."
            echo "newer=false" >> $GITHUB_ENV
          fi

      - name: Filter input files (U1/U2 only)
        if: env.newer == 'true'
        run: |
          mkdir -p tmp_input
          unzip input.zip -d tmp_input/
          cd tmp_input
          # Delete non-U1/U2 files
          find . -type f ! -name 'U1*' ! -name 'U2*' -delete
          # Remove empty directories
          find . -type d -empty -delete
          # Check if any files remain
          if [ -z "$(find . -type f)" ]; then
            echo "Error: No files starting with U1/U2 found in input"
            exit 1
          fi
          zip -r ../filtered_input.zip *
          cd ..
          rm -rf tmp_input input.zip
          
      - name: Prepare NaPTAN data directory
        run: mkdir -p /tmp/transx2gtfs

      - name: Download and package NaPTAN dataset
        run: |
          # Download the CSV file
          curl -L -o /tmp/Stops.csv "https://beta-naptan.dft.gov.uk/Download/National/csv"
          
      - name: Convert to GTFS
        run: transxchange2gtfs filtered_input.zip gtfs-output.zip

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gtfs-output.zip
          git commit -m "Update GTFS file (filtered U1/U2 sources)"
          git push
